# Generated by Django 2.0.9 on 2019-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_auto_20190313_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='業務コード')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='業務名')),
                ('auth_flg', models.BooleanField(default=False, verbose_name='権限')),
            ],
        ),
        migrations.RemoveField(
            model_name='giscustomer',
            name='car',
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='車両型式'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='車両名'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='車検満了日'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='insurance_date',
            field=models.DateField(blank=True, null=True, verbose_name='保険満了日'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='型式'),
        ),
    ]
