# Generated by Django 2.0.9 on 2019-05-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0009_auto_20190426_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop2Detail',
            fields=[
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gis.Shop2')),
                ('open_year_month', models.CharField(blank=True, help_text='例:\u30002019年4月', max_length=25, null=True, verbose_name='開設年月')),
                ('build_passed_year', models.IntegerField(blank=True, help_text='半角数字で入力してください。', null=True, verbose_name='築年数')),
                ('notices', models.CharField(blank=True, max_length=100, null=True, verbose_name='特記事項')),
                ('shop_area', models.CharField(blank=True, help_text='こちらに"自社面積㎡","自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='自社面積㎡,自社面積坪')),
                ('chinshaku_area', models.CharField(blank=True, help_text='こちらに"自社面積㎡","自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='賃借面積㎡,賃借面積坪')),
                ('place_rent', models.IntegerField(blank=True, help_text='半角数字で入力してください。', null=True, verbose_name='土地賃料')),
                ('building_area', models.CharField(blank=True, help_text='こちらに"自社面積㎡","自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='建物面積㎡,建物面積坪')),
                ('floor_area', models.CharField(blank=True, help_text='こちらに"自社面積㎡","自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='延床面積㎡,延床面積坪')),
                ('building_rent', models.IntegerField(blank=True, help_text='半角数字で入力してください。', null=True, verbose_name='建物賃料')),
                ('youto_chiiki', models.CharField(blank=True, max_length=25, null=True, verbose_name='用途地域')),
                ('factory_area', models.IntegerField(blank=True, help_text='半角数字で入力してください。', null=True, verbose_name='工場面積㎡')),
                ('factory_auth', models.CharField(blank=True, max_length=25, null=True, verbose_name='工場認可')),
                ('stalls', models.IntegerField(blank=True, help_text='半角数字で入力してください。', null=True, verbose_name='ストール数')),
                ('members', models.CharField(blank=True, help_text='こちらにカンマ区切りで"店員総数,店長/GM,副店長,営業TM,QA/SC,STM,SAD/TM,EL/WSL,SE/TS,FC/RS,その他"の順番で入力してください。特定の業務スタッフがいない場合は0を入れカンマで区切り、次の業務スタッフ人数を続けて入力してください。', max_length=100, null=True, verbose_name='店員総数,店長/GM,副店長,営業TM,QA/SC,STM,SAD/TM,EL/WSL,SE/TS,FC/RS,その他')),
                ('Y_3', models.CharField(blank=True, help_text='現在より3年前の営業実績（お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数）をカンマ区切りで順番に入力してください。', max_length=100, null=True, verbose_name='-3年度 お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数')),
                ('Y_2', models.CharField(blank=True, help_text='現在より2年前の営業実績（お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数）をカンマ区切りで順番に入力してください。', max_length=100, null=True, verbose_name='-2年度 お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数')),
                ('Y_1', models.CharField(blank=True, help_text='現在より1年前の営業実績（お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数）をカンマ区切りで順番に入力してください。', max_length=100, null=True, verbose_name='-1年度 お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数')),
                ('close_store_P', models.CharField(blank=True, max_length=50, null=True, verbose_name='近隣店舗P')),
                ('close_store_C', models.CharField(blank=True, max_length=50, null=True, verbose_name='近隣店舗C')),
                ('close_store_N', models.CharField(blank=True, max_length=50, null=True, verbose_name='近隣店舗_N')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('feature_store', models.CharField(blank=True, max_length=150, null=True, verbose_name='店舗の将来像')),
            ],
            options={
                'verbose_name_plural': '店舗基本情報データ',
            },
        ),
        migrations.AlterField(
            model_name='shop2',
            name='brand_id',
            field=models.IntegerField(blank=True, help_text='トヨタ系は"14601", レクサス系は"24653からの連番"を入力してください。候補地の場合も予定されるブランド販売店コードを入力してください。', null=True, verbose_name='ブランド販売店コード'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='id',
            field=models.IntegerField(help_text='店舗コードは一意（ユニーク）でなければいけません。半角数字で入力してください。トヨペットは規定店舗コード、カローラは1000からの連番、ネッツは2000からの連番、候補地は3000からの連番で入力してください。', primary_key=True, serialize=False, verbose_name='店舗コード'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='name',
            field=models.CharField(blank=True, help_text='候補地の場合も適当な名前を入力してください。', max_length=100, null=True, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='new_flg',
            field=models.NullBooleanField(help_text='候補地の場合も予定される販売部門を”はい”にしてください。', verbose_name='新車部門あり'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='shop_flg',
            field=models.NullBooleanField(help_text='候補地を含む実店舗の場合はオン、部署などの場合はオフにしてください。', verbose_name='実店舗'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='ucar_flg',
            field=models.NullBooleanField(help_text='候補地の場合も予定される販売部門を”はい”にしてください。', verbose_name='中古車部門あり'),
        ),
    ]
