services:
  db:
    image: mysql:8.0
    container_name: stg_stp00_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: stg_stp00_app
    command: >
      uwsgi
      --socket 0.0.0.0:8001
      --module config.wsgi
      --memory-report
      --processes 4
      --threads 8
    volumes:
      - ./staticfiles:/src/STP00-dev/staticfiles
    expose:
      - "8001"
    env_file:
      - .env
    environment:
      # AWS認証情報
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
      # 環境切り替え（stg or prod）
      - APP_ENV=stg
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    container_name: stg_stp00_nginx
    ports:
      - "8100:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/src/STP00-dev/staticfiles
    depends_on:
      - app
    restart: always

volumes:
  mysql_volume:
