# Generated by Django 2.0.9 on 2019-03-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190313_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(help_text='ここで選ばれた業務に権限が付与されていると商圏機能にアクセスができます。\n業務を入力しない場合は不明を選択してください。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Department', verbose_name='業務権限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='メールアドレスはユニーク(一意)でなければいけません。', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
