# Generated by Django 2.0.9 on 2019-03-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190320_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='<django.db.models.fields.IntegerField>', max_length=100, verbose_name='その他'),
        ),
    ]
