# Generated by Django 2.0.9 on 2019-04-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190402_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'ユーザーマスタデータ'},
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(help_text='ここで選ばれた業務グループに商圏分析権限が付与されていると商圏機能にアクセスができます。\n業務を入力しない場合は不明を選択してください。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Department', verbose_name='業務グループ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='システム管理者'),
        ),
    ]
