# Generated by Django 2.0.9 on 2019-03-13 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成スタッフ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Shop2', verbose_name='活動店舗'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='対象社員'),
        ),
        migrations.AddField(
            model_name='mylistcustomercars',
            name='customer_cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.CustomerCars'),
        ),
        migrations.AddField(
            model_name='mylistcustomercars',
            name='mylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.Mylist2'),
        ),
        migrations.AddField(
            model_name='mylist2',
            name='customer_cars',
            field=models.ManyToManyField(through='gis.MylistCustomerCars', to='gis.CustomerCars'),
        ),
        migrations.AddField(
            model_name='mylist2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mylist',
            name='customers',
            field=models.ManyToManyField(to='gis.Customer'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Car', verbose_name='車両'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='car_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_rank_set', to='gis.Rank', verbose_name='車両層別区分'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='customer_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rank_set', to='gis.Rank', verbose_name='顧客層別区分'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='service_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_shop_user_set', to='gis.Shop2', verbose_name='サービス担当店舗'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_user_set', to='gis.Shop2', verbose_name='担当店舗'),
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Shop2', verbose_name='活動店舗'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ'),
        ),
        migrations.AddField(
            model_name='customercars',
            name='base_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.BaseCustomer', verbose_name='オーナー顧客'),
        ),
        migrations.AddField(
            model_name='customercars',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.Car', verbose_name='車両'),
        ),
        migrations.AddField(
            model_name='customercars',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Rank', verbose_name='顧客層別区分'),
        ),
        migrations.AddField(
            model_name='customercars',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Shop2', verbose_name='担当店舗'),
        ),
        migrations.AddField(
            model_name='customercars',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Shop2', verbose_name='活動店舗'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ'),
        ),
        migrations.AddField(
            model_name='basecustomer',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis.Rank', verbose_name='顧客層別区分'),
        ),
    ]
