# Generated by Django 2.0.9 on 2019-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_auto_20190313_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='auth_flg',
            field=models.BooleanField(default=False, help_text='ここをオンにすると、ユーザー画面でこの業務を持つユーザーが商圏分析機能にアクセスできます。', verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='brand_id',
            field=models.IntegerField(blank=True, help_text='トヨタ系は"14601", レクサス系は24653からの連番を入力してください。', null=True, verbose_name='ブランド販売店コード'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='lat',
            field=models.FloatField(blank=True, help_text='緯度経度は実店舗の場合は必ず入力してください。', null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='lng',
            field=models.FloatField(blank=True, help_text='緯度経度は実店舗の場合は必ず入力してください。', null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='shop_flg',
            field=models.NullBooleanField(help_text='実店舗の場合はオン、部署などの場合はオフにしてください。', verbose_name='実店舗'),
        ),
    ]
