# Generated by Django 2.0.9 on 2019-03-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0004_auto_20190320_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='auth_flg',
            field=models.BooleanField(default=False, help_text='ここをオンにすると、ユーザー画面でこの業務を持つユーザーが商圏分析機能にアクセスできます。', verbose_name='業務権限'),
        ),
        migrations.AlterField(
            model_name='shop2',
            name='brand_id',
            field=models.IntegerField(blank=True, help_text='トヨタ系は"14601", レクサス系は"24653からの連番"を入力してください。', null=True, verbose_name='ブランド販売店コード'),
        ),
    ]
