# Generated by Django 2.0.9 on 2019-03-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0005_auto_20190320_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='giscustomer',
            name='csv_flg',
            field=models.BooleanField(default=False, verbose_name='CSV登録CK'),
        ),
    ]
