# Generated by Django 2.0.9 on 2019-03-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0006_giscustomer_csv_flg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '業務マスタデータ'},
        ),
        migrations.AlterModelOptions(
            name='giscustomer',
            options={'verbose_name_plural': '顧客車両データ'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name_plural': 'ランク層マスタデータ'},
        ),
        migrations.AlterModelOptions(
            name='shop2',
            options={'verbose_name_plural': '店舗マスタデータ'},
        ),
        migrations.RemoveField(
            model_name='giscustomer',
            name='csv_flg',
        ),
        migrations.AlterField(
            model_name='department',
            name='auth_flg',
            field=models.BooleanField(default=False, help_text='ここをオンにすると、ユーザー画面でこの業務を持つユーザーが商圏分析機能にアクセスできます。', verbose_name='商圏分析権限'),
        ),
    ]
