# Generated by Django 2.0.9 on 2019-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0007_auto_20190329_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='giscustomer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shop2',
            options={},
        ),
        migrations.AddField(
            model_name='giscustomer',
            name='csv_flg',
            field=models.BooleanField(default=False, verbose_name='CSV登録CK'),
        ),
        migrations.AlterField(
            model_name='department',
            name='auth_flg',
            field=models.BooleanField(default=False, help_text='ここをオンにすると、ユーザー画面でこの業務を持つユーザーが商圏分析機能にアクセスできます。', verbose_name='業務権限'),
        ),
    ]
