# Generated by Django 2.0.9 on 2019-04-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0008_auto_20190402_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '業務マスタデータ'},
        ),
        migrations.AlterModelOptions(
            name='giscustomer',
            options={'verbose_name_plural': '顧客車両データ'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name_plural': 'ランク層マスタデータ'},
        ),
        migrations.AlterModelOptions(
            name='shop2',
            options={'verbose_name_plural': '店舗マスタデータ'},
        ),
        migrations.AddField(
            model_name='shop2',
            name='shop_kind',
            field=models.IntegerField(default=1, help_text='半角数字で入力してください。トヨペット店は"1", カローラ東海店は"2", ネッツトヨタスルガ店は"3", 候補地として利用は"4"を入力してください。', verbose_name='販売店舗種別'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='auth_flg',
            field=models.BooleanField(default=False, help_text='ここをオンにすると、ユーザー画面でこの業務を持つユーザーが商圏分析機能にアクセスできます。', verbose_name='商圏分析権限'),
        ),
    ]
