# Generated by Django 2.0.9 on 2019-05-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0010_auto_20190509_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop2detail',
            name='Y_1',
            field=models.CharField(blank=True, help_text='現在より1年前の営業実績を\u3000"お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数"\u3000の順番でカンマ区切りで順番に入力してください。(例：5340,75,264,0,136,184)', max_length=100, null=True, verbose_name='-1年度営業実績'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='Y_2',
            field=models.CharField(blank=True, help_text='現在より2年前の営業実績を\u3000"お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数"\u3000の順番でカンマ区切りで順番に入力してください。(例：5340,75,264,0,136,184)', max_length=100, null=True, verbose_name='-2年度営業実績'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='Y_3',
            field=models.CharField(blank=True, help_text='現在より3年前の営業実績を\u3000"お客様数,SA層比率(%),新車販売台数,U-Car販売台数,総整備台数,車検台数"\u3000の順番でカンマ区切りで順番に入力してください。(例：5340,75,264,0,136,184)', max_length=100, null=True, verbose_name='-3年度営業実績'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='building_area',
            field=models.CharField(blank=True, help_text='こちらに"自社面積㎡,自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='建物面積㎡,建物面積坪'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='chinshaku_area',
            field=models.CharField(blank=True, help_text='こちらに"自社面積㎡,自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='賃借面積㎡,賃借面積坪'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='close_store_N',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='近隣店舗N'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='floor_area',
            field=models.CharField(blank=True, help_text='こちらに"自社面積㎡,自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='延床面積㎡,延床面積坪'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='members',
            field=models.CharField(blank=True, help_text='こちらにカンマ区切りで "店員総数,店長/GM,副店長,営業TM,QA/SC,STM,SAD/TM,EL/WSL,SE/TS,FC/RS,その他" の順番で入力してください。特定の業務スタッフがいない場合は0を入れカンマで区切り、次の業務スタッフ人数を続けて入力してください。\n例： 10,1,1,4,2,0,1,1,0,0,0', max_length=100, null=True, verbose_name='店舗人員'),
        ),
        migrations.AlterField(
            model_name='shop2detail',
            name='shop_area',
            field=models.CharField(blank=True, help_text='こちらに"自社面積㎡,自社面積坪"のようにカンマ区切りで半角数字で入力してください。(例：660㎡の200坪の場合\u3000660,200 )', max_length=50, null=True, verbose_name='自社面積㎡,自社面積坪'),
        ),
    ]
