upstream django {
    server app:8001;
}

server {
    listen 80;

    location / {
        include uwsgi_params;
        uwsgi_pass django;
    }

    location /static/ {
        alias /src/STP00-dev/staticfiles/;
    }
}
